baseURL: 'https://hawk-gt1191.de/'
languageCode: 'de-DE'
title: 'HAWK GT1191'

markup:
  goldmark:
    extensions:
      typographer: true
    parser:
      autoHeadingID: true
      autoHeadingIDType: 'github'
      attribute:
        block: true
        title: true
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 2
menu:
  nav:
    - identifier: 'das-seminar'
      name: 'Das Seminar'
      url: '/das-seminar/'
      params:
        class: ''
      weight: 1
    - identifier: 'links'
      name: 'Links'
      url: '/links/'
      params:
        class: ''
      weight: 3
  footer:
    - identifier: 'impressum'
      name: 'Impressum'
      url: '/impressum/'
      weight: 1
    - identifier: 'datenschutz'
      name: 'Datenschutz'
      url: '/datenschutz/'
      weight: 2
