baseURL: 'https://hawk-gt1191.de/'
languageCode: 'de-DE'
title: 'HAWK GT1191'
enableemoji: true
enableGitInfo: true
params:
  links:
    studip: 'https://studip.hawk-hhg.de/dispatch.php/course/details/?cid=92a8299ab61eae0ab48cccd380540adc'
    discordInvite: 'https://discord.gg/Kke2BsapYu'
    discordChannel: 'https://discord.com/channels/789498129765630003'

frontmatter:
  date:
  - date
  - publishDate
  - lastmod
  expiryDate:
  - expiryDate
  lastmod:
  - lastmod
  - :git
  - date
  - publishDate
  publishDate:
  - publishDate
  - date

markup:
  goldmark:
    extensions:
      typographer: true
      taskList: true
      strikethrough: true
      typographer: true
      table: true
      definitionList: true
      highlight: true
    parser:
      autoHeadingID: true
      autoHeadingIDType: 'github'
      attribute:
        block: true
        title: true
    renderer:
      hardWraps: true
      unsafe: true
  tableOfContents:
    endLevel: 3
  highlight:
    noClasses: false

menu:
  nav:
    - identifier: 'seminar'
      name: 'Seminar'
      url: '/seminar/'
      params:
        class: ''
      weight: 1
    # - identifier: 'tutorials'
    #   name: 'Tutorials'
    #   url: '/tutorials/'
    #   params:
    #     class: ''
    #   weight: 2
    - identifier: 'links'
      name: 'Links'
      url: '/links/'
      params:
        class: ''
      weight: 2
    - identifier: 'hilfe'
      name: 'Hilfe'
      url: '/hilfe/'
      params:
        class: ''
      weight: 3
  footer:
    - identifier: 'impressum'
      name: 'Impressum'
      url: '/impressum/'
      weight: 1
    - identifier: 'datenschutz'
      name: 'Datenschutz'
      url: '/datenschutz/'
      weight: 2
