baseURL: 'https://hawk-gt1191.de/'
languageCode: 'de-DE'
title: 'HAWK GT1191'

markup:
  goldmark:
    extensions:
      typographer: true
      taskList: true
      strikethrough: true
      typographer: true
      table: true
      definitionList: true
      highlight: true
    parser:
      autoHeadingID: true
      autoHeadingIDType: 'github'
      attribute:
        block: true
        title: true
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 2
  highlight:
    noClasses: false
menu:
  nav:
    - identifier: 'das-seminar'
      name: 'Das Seminar'
      url: '/das-seminar/'
      params:
        class: ''
      weight: 1
    # - identifier: 'tutorials'
    #   name: 'Tutorials'
    #   url: '/tutorials/'
    #   params:
    #     class: ''
    #   weight: 2
    - identifier: 'links'
      name: 'Links'
      url: '/links/'
      params:
        class: ''
      weight: 3
  footer:
    - identifier: 'impressum'
      name: 'Impressum'
      url: '/impressum/'
      weight: 1
    - identifier: 'datenschutz'
      name: 'Datenschutz'
      url: '/datenschutz/'
      weight: 2
