baseURL = 'https://hawk-gt1191.de/'
languageCode = 'de-DE'
title = 'HAWK GT1191'
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = true
      [markup.goldmark.parser]
        #autoHeadingID = true
        #autoHeadingIDType = 'github'
        [markup.goldmark.parser.attribute]
          block = true
          title = true
[menu]
[[menu.footer]]
  identifier = 'impressum'
  name = 'Impressum'
  url = '/impressum/'
  weight = 1
[[menu.footer]]
  identifier = 'datenschutz'
  name = 'Datenschutz'
  url = '/datenschutz/'
  weight = 2
